"""Measurement service package."""

from specproof_measurement_service.landmarks import (
    T_SHIRT_LANDMARKS,
    Landmark,
    LandmarkName,
    LandmarkSet,
    LandmarkStatus,
    detect_tshirt_landmarks,
    extract_contour_points,
    landmark_recall,
)
from specproof_measurement_service.mesh import (
    IndexedMesh,
    MeshVertex,
    build_indexed_mesh,
    write_indexed_mesh,
)
from specproof_measurement_service.parameterization import (
    SurfaceMapPoint,
    SurfaceParameterization,
    mapping_by_pixel,
    parameterize_surface,
)
from specproof_measurement_service.pipeline import (
    PerceptionBoundingBox,
    PerceptionLandmark,
    PerceptionMesh,
    PerceptionPipeline,
    PerceptionResult,
    PerceptionSurfaceMapping,
    PerceptionSurfaceMapPoint,
    PerceptionSurfaceQuality,
    estimate_background_from_border,
    write_perception_result,
)
from specproof_measurement_service.point_cloud import (
    PlaneModel,
    detect_support_plane,
    estimate_normals,
    organized_point_cloud,
    separate_garment_from_plane,
)
from specproof_measurement_service.preprocessing import (
    BackgroundModel,
    PreprocessingResult,
    build_background_model,
    filter_depth,
    preprocess_rgbd,
    refine_rgb_depth_registration,
    smooth_color,
    subtract_background,
)
from specproof_measurement_service.result import MeasurementResult
from specproof_measurement_service.segmentation import (
    BoundingBox,
    GarmentCategory,
    GarmentOrientation,
    SegmentationResult,
    classify_garment,
    compute_bounding_box,
    detect_orientation,
    extract_boundary,
    largest_connected_component,
    segment_garment,
    segmentation_iou,
)
from specproof_measurement_service.surface import SurfaceConfidence, score_surface_confidence

__all__ = [
    "BackgroundModel",
    "BoundingBox",
    "GarmentCategory",
    "GarmentOrientation",
    "IndexedMesh",
    "Landmark",
    "LandmarkName",
    "LandmarkSet",
    "LandmarkStatus",
    "MeasurementResult",
    "MeshVertex",
    "PerceptionBoundingBox",
    "PerceptionLandmark",
    "PerceptionPipeline",
    "PerceptionResult",
    "PerceptionMesh",
    "PerceptionSurfaceMapPoint",
    "PerceptionSurfaceMapping",
    "PerceptionSurfaceQuality",
    "PlaneModel",
    "PreprocessingResult",
    "SegmentationResult",
    "SurfaceConfidence",
    "SurfaceMapPoint",
    "SurfaceParameterization",
    "T_SHIRT_LANDMARKS",
    "build_background_model",
    "build_indexed_mesh",
    "classify_garment",
    "compute_bounding_box",
    "detect_support_plane",
    "detect_orientation",
    "detect_tshirt_landmarks",
    "estimate_background_from_border",
    "estimate_normals",
    "extract_contour_points",
    "extract_boundary",
    "filter_depth",
    "landmark_recall",
    "largest_connected_component",
    "mapping_by_pixel",
    "organized_point_cloud",
    "parameterize_surface",
    "preprocess_rgbd",
    "refine_rgb_depth_registration",
    "segment_garment",
    "segmentation_iou",
    "separate_garment_from_plane",
    "smooth_color",
    "score_surface_confidence",
    "subtract_background",
    "write_perception_result",
    "write_indexed_mesh",
]
